### ISSUE TITLE
Not process all characters pasted from clipboard

### ISSUE THREAD

**Issue by ppastercik** [andyduke/console-keyboard#11]
### Description

If I run the [sample code](https://github.com/andyduke/console-keyboard/blob/master/examples/show_codes.php) and try to paste the string `test` from the clipboard, not all characters are processed.

### Current output

```
Press any key to display key code or press Q to exit:

t (84)

Exit.
```

### Expected output

```
Press any key to display key code or press Q to exit:

t (84)
e (69)
s (83)
t (84)

Exit.
```

**Comment by andyduke** [comment]
@ppastercik Does this problem occur on Windows, Linux or MacOS?

**Comment by ppastercik** [comment]
@andyduke 
The problem was in Windows and the other problem with the clipboard was in Linux.

Both problems are fixed in the master branch. It works in Windows and Linux. I cannot test macOS.
