### ISSUE TITLE
Ctrl+C not working properly on bash shells on Windows

### ISSUE THREAD

**Issue by ppastercik** [andyduke/console-keyboard#12]
### Description

If I run the [sample code](https://github.com/andyduke/console-keyboard/blob/master/examples/show_codes.php) on some terminals / emulators (listed below) and try to exit the program using `Ctrl+C`, then I have to press some other key for the program to actually exit (print `Exit.` and exit the script).

#### Tested terminals / emulators on which it does not work properly

- ConEmu - Msys2
- Cygwin64 Terminal
- Git Bash
  - does not work if Git Bash is running standalone
  - works if running Git Bash within Windows Terminal
- MobaXterm - Bash
  - run with `winpty php index.php`
- MobaXterm - SSH
- PuTTY
- ZOC8 Terminal

### Operating system

Windows

### Expected behaviour

When I press `Ctrl+C`, it immediately prints `Exit.` and exits the script.

### Possible solution

Disable `ENABLE_PROCESSED_INPUT`, process `Ctrl+C` as a normal character and stop reading keys when processing this character.

**Comment by andyduke** [comment]
@ppastercik Thank you for describing the problem in detail. Can you check if the fix from the master branch works?

**Comment by ppastercik** [comment]
@andyduke The fix from the master branch works.
