### ISSUE TITLE
Ctrl+C not working properly on Linux

### ISSUE THREAD

**Issue by ppastercik** [andyduke/console-keyboard#13]
### Description

If I run the [sample code](https://github.com/andyduke/console-keyboard/blob/master/examples/show_codes.php) on Linux and try to exit the program using `Ctrl+C`, the script stops immediately without echo `Exit.` .

### Operating system

WSL2 - Ubuntu 20.04.3 LTS
Ubuntu 18.04.5 LTS

### Expected behaviour
When I press Ctrl+C, it prints `Exit.` and exits the script.

### Possible solution
Disable `isig` by `stty`, process Ctrl+C as a normal character and stop reading keys when processing this character.

**Comment by andyduke** [comment]
@ppastercik Can you check if the fix from the master branch works?

**Comment by ppastercik** [comment]
@andyduke The fix from the master branch works.
