### ISSUE TITLE
Better keys mapping (without using json_decode)

### ISSUE THREAD

**Issue by ppastercik** [andyduke/console-keyboard#14]
### Description

For example, this line in https://github.com/andyduke/console-keyboard/blob/master/src/AnsiKeyboard.php:
`'\u001b[A' => self::UP,`
We can replace it with this (without need of using `json_decode`):
`"\u{001b}[A" => self::UP`

See the ["Double quoted" section of the string documentation](https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.double).

This will also allow you to remove `$asciiMap` and use only `$unicodeMap`. Or is this split on purpose?

**Comment by andyduke** [comment]
@ppastercik You are right, removing json_decode would be better, just like getting rid of $asciiMap and $unicodeMap.
